USE ROLE TRAINING_ROLE;
USE WAREHOUSE MONKEY_WH;
USE DATABASE MONKEY_DB;
USE SCHEMA FINAL_PROJECT;

SELECT
    COALESCE(source_name, 'UNKNOWN') AS source_name,
    COUNT(*) AS article_count
FROM raw_articles
GROUP BY 1
ORDER BY article_count DESC
LIMIT 15;